spring.application.name=RastroLocal

server.port=

spring.datasource.url=jdbc:mysql://localhost:3306/rastrolocal
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.profiles.active=production
